[project]
name = "lab_03"
version = "0.1.0"
description = ""
authors = [
    {name = "David Krauthamer", email = "dkrautha@pm.me"},
]
license = {text = "GPL-3.0+"}

[tool.ruff]
select = ["E", "F", "I"]
